package envtemplate_test

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/xico42/devenv/internal/envtemplate"
)

// helper — add outside any Test func
func writeTempEnv(t *testing.T, content string) string {
	t.Helper()
	f := filepath.Join(t.TempDir(), ".env")
	if err := os.WriteFile(f, []byte(content), 0o600); err != nil {
		t.Fatalf("WriteFile: %v", err)
	}
	return f
}

func TestParseEnvFile(t *testing.T) {
	t.Run("normal key-value pairs", func(t *testing.T) {
		f := writeTempEnv(t, "KEY=value\nFOO=bar\n")
		got, err := envtemplate.ParseEnvFile(f)
		if err != nil {
			t.Fatalf("ParseEnvFile() error = %v", err)
		}
		if got["KEY"] != "value" {
			t.Errorf("KEY = %q, want %q", got["KEY"], "value")
		}
		if got["FOO"] != "bar" {
			t.Errorf("FOO = %q, want %q", got["FOO"], "bar")
		}
	})

	t.Run("skips comments and blank lines", func(t *testing.T) {
		f := writeTempEnv(t, "# comment\n\nKEY=value\n")
		got, err := envtemplate.ParseEnvFile(f)
		if err != nil {
			t.Fatalf("ParseEnvFile() error = %v", err)
		}
		if len(got) != 1 {
			t.Errorf("len = %d, want 1; got %v", len(got), got)
		}
	})

	t.Run("value with equals sign splits on first only", func(t *testing.T) {
		f := writeTempEnv(t, "URL=postgres://user:pass@host/db?opt=val\n")
		got, err := envtemplate.ParseEnvFile(f)
		if err != nil {
			t.Fatalf("ParseEnvFile() error = %v", err)
		}
		want := "postgres://user:pass@host/db?opt=val"
		if got["URL"] != want {
			t.Errorf("URL = %q, want %q", got["URL"], want)
		}
	})

	t.Run("missing file returns error", func(t *testing.T) {
		_, err := envtemplate.ParseEnvFile("/nonexistent/path/.env")
		if err == nil {
			t.Fatal("ParseEnvFile() error = nil, want error for missing file")
		}
	})
}

func TestProcess(t *testing.T) {
	ctx := envtemplate.EnvTemplateContext{
		Project:      "myapp",
		Branch:       "feature",
		WorktreePath: "/home/user/projects/myapp__worktrees/feature",
		SessionName:  "myapp-feature",
	}

	t.Run("context fields render", func(t *testing.T) {
		tmpl := "{{ .Project }} {{ .Branch }} {{ .WorktreePath }} {{ .SessionName }}"
		got, err := envtemplate.Process(tmpl, "test", ctx)
		if err != nil {
			t.Fatalf("Process() error = %v", err)
		}
		for _, want := range []string{"myapp", "feature", "/home/user/projects/myapp__worktrees/feature", "myapp-feature"} {
			if !strings.Contains(got, want) {
				t.Errorf("output missing %q\ngot:\n%s", want, got)
			}
		}
	})

	t.Run("port matches DeterministicPort", func(t *testing.T) {
		got, err := envtemplate.Process(`{{ port "api" }}`, "test", ctx)
		if err != nil {
			t.Fatalf("Process() error = %v", err)
		}
		expected := fmt.Sprintf("%d", envtemplate.DeterministicPort("myapp", "feature", "api"))
		if !strings.Contains(got, expected) {
			t.Errorf("port output %q does not contain %q", got, expected)
		}
	})

	t.Run("port same name same value in output", func(t *testing.T) {
		got, err := envtemplate.Process(`A={{ port "api" }} B={{ port "api" }}`, "test", ctx)
		if err != nil {
			t.Fatalf("Process() error = %v", err)
		}
		expected := fmt.Sprintf("%d", envtemplate.DeterministicPort("myapp", "feature", "api"))
		if strings.Count(got, expected) < 2 {
			t.Errorf("expected port %s to appear twice in:\n%s", expected, got)
		}
	})

	t.Run("env returns set var", func(t *testing.T) {
		t.Setenv("DEVENV_TEST_SECRET", "mysecret")
		got, err := envtemplate.Process(`{{ env "DEVENV_TEST_SECRET" "default" }}`, "test", ctx)
		if err != nil {
			t.Fatalf("Process() error = %v", err)
		}
		if !strings.Contains(got, "mysecret") {
			t.Errorf("output missing env var value\ngot:\n%s", got)
		}
	})

	t.Run("env unset var uses default", func(t *testing.T) {
		got, err := envtemplate.Process(`{{ env "DEVENV_UNSET_VAR_12345" "mydefault" }}`, "test", ctx)
		if err != nil {
			t.Fatalf("Process() error = %v", err)
		}
		if !strings.Contains(got, "mydefault") {
			t.Errorf("output missing default value\ngot:\n%s", got)
		}
	})

	t.Run("env unset var no default returns empty string", func(t *testing.T) {
		got, err := envtemplate.Process(`A={{ env "DEVENV_UNSET_VAR_12345" }}B`, "test", ctx)
		if err != nil {
			t.Fatalf("Process() error = %v", err)
		}
		if !strings.Contains(got, "A=B") {
			t.Errorf("expected empty string for unset var, got:\n%s", got)
		}
	})

	t.Run("header present in output", func(t *testing.T) {
		got, err := envtemplate.Process("KEY=value", "repo-local", ctx)
		if err != nil {
			t.Fatalf("Process() error = %v", err)
		}
		if !strings.HasPrefix(got, "# Generated by devenv") {
			t.Errorf("output missing generated header\ngot:\n%s", got)
		}
		if !strings.Contains(got, "repo-local") {
			t.Errorf("output missing source in header\ngot:\n%s", got)
		}
	})

	t.Run("template syntax error returns error", func(t *testing.T) {
		_, err := envtemplate.Process("{{ .Invalid }", "test", ctx)
		if err == nil {
			t.Fatal("Process() error = nil, want error for syntax error")
		}
	})

	t.Run("template execute error returns error", func(t *testing.T) {
		// Accessing a nonexistent field fails at execute time (not parse time).
		tmpl := `{{ .NonExistentField }}`
		_, err := envtemplate.Process(tmpl, "test", ctx)
		if err == nil {
			t.Fatal("Process() error = nil, want error for execute-time error")
		}
	})
}

func TestDeterministicPort(t *testing.T) {
	t.Run("idempotent", func(t *testing.T) {
		p1 := envtemplate.DeterministicPort("myapp", "feature", "api")
		p2 := envtemplate.DeterministicPort("myapp", "feature", "api")
		if p1 != p2 {
			t.Errorf("not idempotent: %d != %d", p1, p2)
		}
	})

	t.Run("in range 10000-59999", func(t *testing.T) {
		p := envtemplate.DeterministicPort("myapp", "feature", "api")
		if p < 10000 || p > 59999 {
			t.Errorf("port %d out of range 10000-59999", p)
		}
	})

	t.Run("different name gives different port", func(t *testing.T) {
		p1 := envtemplate.DeterministicPort("myapp", "feature", "api")
		p2 := envtemplate.DeterministicPort("myapp", "feature", "db")
		if p1 == p2 {
			t.Errorf("same port %d for different names", p1)
		}
	})

	t.Run("null-byte separation prevents ambiguity", func(t *testing.T) {
		// ("ab","cd","x") must differ from ("a","bcd","x")
		p1 := envtemplate.DeterministicPort("ab", "cd", "x")
		p2 := envtemplate.DeterministicPort("a", "bcd", "x")
		if p1 == p2 {
			t.Errorf("null-byte separation failed: both hashed to %d", p1)
		}
	})
}
