package envtemplate

import (
	"bytes"
	"fmt"
	"hash/fnv"
	"os"
	"strings"
	"text/template"
)

// ParseEnvFile reads a .env file and returns key-value pairs.
// Skips blank lines and lines starting with "#".
// Splits on the first "=" only — values may contain "=".
func ParseEnvFile(path string) (map[string]string, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("reading env file: %w", err)
	}
	result := make(map[string]string)
	for _, line := range strings.Split(string(data), "\n") {
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		idx := strings.Index(line, "=")
		if idx < 0 {
			continue
		}
		result[line[:idx]] = line[idx+1:]
	}
	return result, nil
}

// EnvTemplateContext holds the values available to .env templates.
type EnvTemplateContext struct {
	Project      string // project name from config (e.g. "myapp")
	Branch       string // branch name (e.g. "feature")
	WorktreePath string // absolute path to worktree
	SessionName  string // "<project>-<branch>"
}

// Process renders a .env.template string with the given context and returns
// the full .env file content, including a generated header comment.
// source describes where the template came from (e.g. "repo-local", "/path/to/file").
func Process(templateContent, source string, ctx EnvTemplateContext) (string, error) {
	funcMap := template.FuncMap{
		"port": func(name string) int {
			return DeterministicPort(ctx.Project, ctx.Branch, name)
		},
		"env": func(args ...string) string {
			if len(args) == 0 {
				return ""
			}
			// treat empty string as unset — consistent with shell "or-default" pattern
			if v := os.Getenv(args[0]); v != "" {
				return v
			}
			if len(args) > 1 {
				return args[1]
			}
			return ""
		},
	}

	tmpl, err := template.New("env").Funcs(funcMap).Parse(templateContent)
	if err != nil {
		return "", fmt.Errorf("parsing template: %w", err)
	}

	var buf bytes.Buffer
	fmt.Fprintf(&buf, "# Generated by devenv — do not edit (regenerate with: devenv worktree env %s %s)\n", ctx.Project, ctx.Branch)
	fmt.Fprintf(&buf, "# Template: %s\n\n", source)

	if err := tmpl.Execute(&buf, ctx); err != nil {
		return "", fmt.Errorf("executing template: %w", err)
	}

	return buf.String(), nil
}

// DeterministicPort returns a stable port for the given project/branch/name.
// Uses FNV-1a 32-bit hash with null-byte separators. Range: 10000–59999.
func DeterministicPort(project, branch, name string) int {
	key := project + "\x00" + branch + "\x00" + name
	h := fnv.New32a()
	h.Write([]byte(key))
	return int(h.Sum32()%50000) + 10000
}
